name: unit_tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test GCC
        run : |
          export CMAKE_C_COMPILER=gcc
          export CMAKE_CXX_COMPILER=g++
          cd tools 
          ./tests.sh
      - name: Test Clang
        run : |
          export CMAKE_C_COMPILER=clang
          export CMAKE_CXX_COMPILER=clang++
          cd tools 
          ./tests.sh
